name: route_e_commerce_v2
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_native_splash:
  icons_launcher:
  flutter_bloc:
  icons_plus:
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_svg: ^2.2.3
  google_fonts: ^6.3.3
  dots_indicator: ^4.0.1
  cached_network_image: ^3.4.1
  retrofit: ^4.0.1
  flutter_screenutil: ^5.9.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  logger: ^2.6.2
  json_annotation: ^4.9.0
  awesome_snackbar_content:
  lottie: ^3.3.2
  dio: ^5.9.0
  get_it: ^9.2.0
  injectable: ^2.7.1+2
  dartz: ^0.10.1
  shared_preferences: ^2.5.4
  equatable: ^2.0.7


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0
  retrofit_generator: ^7.0.8
  injectable_generator: ^2.6.2
  build_runner: ^2.4.6
  analyzer: ^6.4.1

  #injectable_generator: ^4.1.1
  #retrofit_generator: ^7.0.1
  json_serializable: ^6.7.1
  #build_runner: ^2.4.6
 # analyzer:




flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/svgs/
