// Mocks generated by Mockito 5.4.4 from annotations
// in route_e_commerce_v2/test/features/auth/forget_password/domain/usecase/verify_email/verify_email_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:route_e_commerce_v2/core/error_handling/error_handling.dart'
    as _i5;
import 'package:route_e_commerce_v2/features/auth/forget_password/data/models/verify_email/verify_email_request.dart'
    as _i7;
import 'package:route_e_commerce_v2/features/auth/forget_password/data/models/verify_email/verify_email_response.dart'
    as _i6;
import 'package:route_e_commerce_v2/features/auth/forget_password/domain/repository/verify_email/verify_email_repo.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [VerifyEmailRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockVerifyEmailRepository extends _i1.Mock
    implements _i3.VerifyEmailRepository {
  @override
  _i4.Future<_i2.Either<_i5.CommerceFailure, _i6.VerifyEmailResponse>>
  verifyEmail(_i7.VerifyEmailRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#verifyEmail, [request]),
            returnValue: _i4.Future<
              _i2.Either<_i5.CommerceFailure, _i6.VerifyEmailResponse>
            >.value(
              _FakeEither_0<_i5.CommerceFailure, _i6.VerifyEmailResponse>(
                this,
                Invocation.method(#verifyEmail, [request]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<
              _i2.Either<_i5.CommerceFailure, _i6.VerifyEmailResponse>
            >.value(
              _FakeEither_0<_i5.CommerceFailure, _i6.VerifyEmailResponse>(
                this,
                Invocation.method(#verifyEmail, [request]),
              ),
            ),
          )
          as _i4.Future<
            _i2.Either<_i5.CommerceFailure, _i6.VerifyEmailResponse>
          >);
}
