// Mocks generated by Mockito 5.4.4 from annotations
// in route_e_commerce_v2/test/features/auth/forget_password/domain/usecase/reset_code/reset_code_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:route_e_commerce_v2/core/error_handling/error_handling.dart'
    as _i5;
import 'package:route_e_commerce_v2/features/auth/forget_password/data/models/verify_email/reset_code_response.dart'
    as _i6;
import 'package:route_e_commerce_v2/features/auth/forget_password/data/models/verify_email/rest_code_request.dart'
    as _i7;
import 'package:route_e_commerce_v2/features/auth/forget_password/domain/repository/reset_code/reset_code_repo.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ResetCodeRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockResetCodeRepo extends _i1.Mock implements _i3.ResetCodeRepo {
  @override
  _i4.Future<_i2.Either<_i5.CommerceFailure, _i6.ResetCodeResponse>> resetCode(
          _i7.RestCodeRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetCode,
          [request],
        ),
        returnValue: _i4.Future<
                _i2.Either<_i5.CommerceFailure, _i6.ResetCodeResponse>>.value(
            _FakeEither_0<_i5.CommerceFailure, _i6.ResetCodeResponse>(
          this,
          Invocation.method(
            #resetCode,
            [request],
          ),
        )),
        returnValueForMissingStub: _i4.Future<
                _i2.Either<_i5.CommerceFailure, _i6.ResetCodeResponse>>.value(
            _FakeEither_0<_i5.CommerceFailure, _i6.ResetCodeResponse>(
          this,
          Invocation.method(
            #resetCode,
            [request],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.CommerceFailure, _i6.ResetCodeResponse>>);
}
